name: feature_lms
description: LMS feature - content, attendance, tests (Vyuh + Sanity)
version: 1.0.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  go_router: ^17.0.0
  vyuh_core: ^1.51.0
  sanity_client: ^1.9.1
  multi_select_flutter: ^4.1.3
  http: ^1.2.0
  mobx: ^2.6.0
  flutter_mobx: ^2.3.0
  google_fonts: ^6.0.0
  flutter_staggered_grid_view: ^0.7.0
  fl_chart: ^0.65.0
  pdf: ^3.10.7
  printing: ^5.12.0
  url_launcher: ^6.2.0
  file_picker: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mobx_codegen: ^2.5.0
  build_runner: ^2.4.0


