name: feature_lms
description: LMS feature - content, attendance, tests (Vyuh + Sanity)
version: 1.0.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^17.0.0
  vyuh_core: ^1.51.0
  sanity_client: ^1.9.1
  multi_select_flutter: ^4.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


